DEEPSORT:
  REID_CKPT: "deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.3
  MIN_CONFIDENCE: 0.4     # confidenza per la detection
  NMS_MAX_OVERLAP: 0.85
  MAX_IOU_DISTANCE: 0.8
  MAX_AGE: 48              #  numero di frames prima di eliminare un track
  N_INIT: 3
  NN_BUDGET: 48
  
## La distance metric restituisce una matrice in cui l'elemento i,j rappresenta il costo nell'associare il track i con la detection j.
## Se il costo è maggiore di MAX_DIST, allora il track e la detection vengono ignorati (vengono cioè segnati come unmatched)